package com.dungeoncrawler.wearos.domain.catalog

import com.dungeoncrawler.wearos.domain.model.EquipmentItem
import com.dungeoncrawler.wearos.domain.model.EquipmentSlot
import com.dungeoncrawler.wearos.domain.model.ItemPassive
import com.dungeoncrawler.wearos.domain.model.Rarity
import com.dungeoncrawler.wearos.domain.model.StatBlock

/**
 * Per-dungeon loot tables: 20 pieces each, matching the 20 monsters that can drop them.
 *
 * Items are grouped into families — a family is one piece of gear appearing at several rarities
 * (`Lame d'ossement` → `affûtée` → `runique`), so a player who keeps farming a dungeon sees the
 * same silhouette get better rather than a shapeless pile of unrelated names.
 *
 * Raw stats are written at their COMMON-tier value and scaled by [Rarity.statMultiplier] when
 * the item is built; percentage stats are never scaled (see [StatBlock.times]).
 *
 * GENERATED — edit `tools/gear/gear_data.py` and re-run `build_gear.py`, which refuses to
 * emit this file if any item breaks its rarity's secondary-bonus contract.
 */
object DungeonGearCatalog {

    /** The 20 pieces that only drop inside [DungeonCatalog.CRYPT]. */
    val CRYPT_GEAR: List<EquipmentItem> = listOf(
        EquipmentItem(
            id = "crypt_bone_blade_common",
            name = "Lame d'ossement",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.COMMON,
            stats = StatBlock(attack = 8),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_bone_blade_common",
            dungeonId = "dng_crypt",
            family = "crypt_bone_blade",
        ),
        EquipmentItem(
            id = "crypt_bone_blade_uncommon",
            name = "Lame d'ossement affûtée",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(attack = 14, critRate = 6),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_bone_blade_uncommon",
            dungeonId = "dng_crypt",
            family = "crypt_bone_blade",
        ),
        EquipmentItem(
            id = "crypt_bone_blade_rare",
            name = "Lame d'ossement runique",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.RARE,
            stats = StatBlock(attack = 19, critRate = 9, armorPierce = 12),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_bone_blade_rare",
            dungeonId = "dng_crypt",
            family = "crypt_bone_blade",
        ),
        EquipmentItem(
            id = "crypt_gravedigger_uncommon",
            name = "Faux du fossoyeur",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(attack = 15, lifeSteal = 5),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_gravedigger_uncommon",
            dungeonId = "dng_crypt",
            family = "crypt_gravedigger",
        ),
        EquipmentItem(
            id = "crypt_gravedigger_epic",
            name = "Faux du fossoyeur damné",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.EPIC,
            stats = StatBlock(attack = 24, lifeSteal = 11, critDamage = 25, hpRegen = 3),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_gravedigger_epic",
            dungeonId = "dng_crypt",
            family = "crypt_gravedigger",
        ),
        EquipmentItem(
            id = "crypt_censer_rare",
            name = "Encensoir de cendres",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.RARE,
            stats = StatBlock(attack = 17, magicPower = 9, critRate = 7),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_censer_rare",
            dungeonId = "dng_crypt",
            family = "crypt_censer",
        ),
        EquipmentItem(
            id = "crypt_first_king_legendary",
            name = "Sceptre du Premier Enseveli",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.LEGENDARY,
            stats = StatBlock(attack = 30, critRate = 14, critDamage = 45, lifeSteal = 14),
            passive = ItemPassive.LIFE_STEAL,
            healPercent = 0f,
            iconRes = "gear_crypt_first_king_legendary",
            dungeonId = "dng_crypt",
            family = "crypt_first_king",
        ),
        EquipmentItem(
            id = "crypt_shroud_common",
            name = "Suaire élimé",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.COMMON,
            stats = StatBlock(maxHp = 45),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_shroud_common",
            dungeonId = "dng_crypt",
            family = "crypt_shroud",
        ),
        EquipmentItem(
            id = "crypt_shroud_uncommon",
            name = "Suaire des veilleurs",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(maxHp = 85, defense = 7),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_shroud_uncommon",
            dungeonId = "dng_crypt",
            family = "crypt_shroud",
        ),
        EquipmentItem(
            id = "crypt_shroud_rare",
            name = "Suaire du chœur muet",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.RARE,
            stats = StatBlock(maxHp = 120, defense = 12, dodge = 6),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_shroud_rare",
            dungeonId = "dng_crypt",
            family = "crypt_shroud",
        ),
        EquipmentItem(
            id = "crypt_ossuary_plate_rare",
            name = "Plates d'ossuaire",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.RARE,
            stats = StatBlock(maxHp = 135, defense = 15, thorns = 10),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_ossuary_plate_rare",
            dungeonId = "dng_crypt",
            family = "crypt_ossuary_plate",
        ),
        EquipmentItem(
            id = "crypt_ossuary_plate_epic",
            name = "Plates d'ossuaire scellées",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.EPIC,
            stats = StatBlock(maxHp = 200, defense = 24, thorns = 18, damageReduction = 6),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_ossuary_plate_epic",
            dungeonId = "dng_crypt",
            family = "crypt_ossuary_plate",
        ),
        EquipmentItem(
            id = "crypt_widow_legendary",
            name = "Corset de la Veuve",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.LEGENDARY,
            stats = StatBlock(maxHp = 230, defense = 26, dodge = 14, thorns = 22),
            passive = ItemPassive.RIPOSTE,
            healPercent = 0f,
            iconRes = "gear_crypt_widow_legendary",
            dungeonId = "dng_crypt",
            family = "crypt_widow",
        ),
        EquipmentItem(
            id = "crypt_candle_ring_common",
            name = "Anneau de cire",
            slot = EquipmentSlot.RING,
            rarity = Rarity.COMMON,
            stats = StatBlock(critRate = 5),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_candle_ring_common",
            dungeonId = "dng_crypt",
            family = "crypt_candle_ring",
        ),
        EquipmentItem(
            id = "crypt_candle_ring_uncommon",
            name = "Anneau de cire ardente",
            slot = EquipmentSlot.RING,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(critRate = 9, critDamage = 18),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_candle_ring_uncommon",
            dungeonId = "dng_crypt",
            family = "crypt_candle_ring",
        ),
        EquipmentItem(
            id = "crypt_grave_ring_rare",
            name = "Chevalière du caveau",
            slot = EquipmentSlot.RING,
            rarity = Rarity.RARE,
            stats = StatBlock(critRate = 11, critDamage = 24, lootBonus = 8),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_grave_ring_rare",
            dungeonId = "dng_crypt",
            family = "crypt_grave_ring",
        ),
        EquipmentItem(
            id = "crypt_grave_ring_epic",
            name = "Chevalière du caveau profané",
            slot = EquipmentSlot.RING,
            rarity = Rarity.EPIC,
            stats = StatBlock(critRate = 15, critDamage = 38, lootBonus = 14, attack = 6),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_grave_ring_epic",
            dungeonId = "dng_crypt",
            family = "crypt_grave_ring",
        ),
        EquipmentItem(
            id = "crypt_whisper_uncommon",
            name = "Fiole de murmures",
            slot = EquipmentSlot.RELIC,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(magicPower = 13, hpRegen = 2),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_whisper_uncommon",
            dungeonId = "dng_crypt",
            family = "crypt_whisper",
        ),
        EquipmentItem(
            id = "crypt_whisper_epic",
            name = "Fiole de murmures anciens",
            slot = EquipmentSlot.RELIC,
            rarity = Rarity.EPIC,
            stats = StatBlock(magicPower = 26, hpRegen = 5, defense = 9, lootBonus = 10),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_crypt_whisper_epic",
            dungeonId = "dng_crypt",
            family = "crypt_whisper",
        ),
        EquipmentItem(
            id = "crypt_crypt_draught_uncommon",
            name = "Élixir de sépulture",
            slot = EquipmentSlot.CONSUMABLE,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock.EMPTY,
            passive = ItemPassive.NONE,
            healPercent = 0.65f,
            iconRes = "gear_crypt_crypt_draught_uncommon",
            dungeonId = "dng_crypt",
            family = "crypt_crypt_draught",
        ),
    )
    /** The 20 pieces that only drop inside [DungeonCatalog.FORGE]. */
    val FORGE_GEAR: List<EquipmentItem> = listOf(
        EquipmentItem(
            id = "forge_obsidian_edge_common",
            name = "Tranchant d'obsidienne",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.COMMON,
            stats = StatBlock(attack = 13),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_obsidian_edge_common",
            dungeonId = "dng_forge",
            family = "forge_obsidian_edge",
        ),
        EquipmentItem(
            id = "forge_obsidian_edge_uncommon",
            name = "Tranchant d'obsidienne trempé",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(attack = 21, armorPierce = 10),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_obsidian_edge_uncommon",
            dungeonId = "dng_forge",
            family = "forge_obsidian_edge",
        ),
        EquipmentItem(
            id = "forge_obsidian_edge_rare",
            name = "Tranchant d'obsidienne noire",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.RARE,
            stats = StatBlock(attack = 28, armorPierce = 18, critDamage = 22),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_obsidian_edge_rare",
            dungeonId = "dng_forge",
            family = "forge_obsidian_edge",
        ),
        EquipmentItem(
            id = "forge_forge_hammer_uncommon",
            name = "Marteau de fonderie",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(attack = 23, thorns = 8),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_forge_hammer_uncommon",
            dungeonId = "dng_forge",
            family = "forge_forge_hammer",
        ),
        EquipmentItem(
            id = "forge_forge_hammer_epic",
            name = "Marteau du contremaître",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.EPIC,
            stats = StatBlock(attack = 34, thorns = 16, critDamage = 32, defense = 8),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_forge_hammer_epic",
            dungeonId = "dng_forge",
            family = "forge_forge_hammer",
        ),
        EquipmentItem(
            id = "forge_molten_lash_rare",
            name = "Fouet de magma",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.RARE,
            stats = StatBlock(attack = 26, lifeSteal = 9, critRate = 8),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_molten_lash_rare",
            dungeonId = "dng_forge",
            family = "forge_molten_lash",
        ),
        EquipmentItem(
            id = "forge_vulcan_legendary",
            name = "Marteau Primordial de Vulcan",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.LEGENDARY,
            stats = StatBlock(attack = 44, armorPierce = 30, critDamage = 55, thorns = 20),
            passive = ItemPassive.ARMOR_PIERCE,
            healPercent = 0f,
            iconRes = "gear_forge_vulcan_legendary",
            dungeonId = "dng_forge",
            family = "forge_vulcan",
        ),
        EquipmentItem(
            id = "forge_slag_mail_common",
            name = "Cotte de scorie",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.COMMON,
            stats = StatBlock(maxHp = 70),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_slag_mail_common",
            dungeonId = "dng_forge",
            family = "forge_slag_mail",
        ),
        EquipmentItem(
            id = "forge_slag_mail_uncommon",
            name = "Cotte de scorie durcie",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(maxHp = 120, defense = 11),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_slag_mail_uncommon",
            dungeonId = "dng_forge",
            family = "forge_slag_mail",
        ),
        EquipmentItem(
            id = "forge_slag_mail_rare",
            name = "Cotte de scorie vitrifiée",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.RARE,
            stats = StatBlock(maxHp = 165, defense = 18, damageReduction = 5),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_slag_mail_rare",
            dungeonId = "dng_forge",
            family = "forge_slag_mail",
        ),
        EquipmentItem(
            id = "forge_glass_carapace_rare",
            name = "Carapace de verre noir",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.RARE,
            stats = StatBlock(maxHp = 175, defense = 20, thorns = 14),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_glass_carapace_rare",
            dungeonId = "dng_forge",
            family = "forge_glass_carapace",
        ),
        EquipmentItem(
            id = "forge_glass_carapace_epic",
            name = "Carapace du golem fondu",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.EPIC,
            stats = StatBlock(maxHp = 255, defense = 31, thorns = 24, damageReduction = 8),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_glass_carapace_epic",
            dungeonId = "dng_forge",
            family = "forge_glass_carapace",
        ),
        EquipmentItem(
            id = "forge_blast_heart_legendary",
            name = "Plastron du Haut-Fourneau",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.LEGENDARY,
            stats = StatBlock(maxHp = 300, defense = 35, damageReduction = 14, hpRegen = 8),
            passive = ItemPassive.DAMAGE_REDUCTION,
            healPercent = 0f,
            iconRes = "gear_forge_blast_heart_legendary",
            dungeonId = "dng_forge",
            family = "forge_blast_heart",
        ),
        EquipmentItem(
            id = "forge_ember_ring_common",
            name = "Anneau de braise",
            slot = EquipmentSlot.RING,
            rarity = Rarity.COMMON,
            stats = StatBlock(critRate = 7),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_ember_ring_common",
            dungeonId = "dng_forge",
            family = "forge_ember_ring",
        ),
        EquipmentItem(
            id = "forge_ember_ring_uncommon",
            name = "Anneau de braise vive",
            slot = EquipmentSlot.RING,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(critRate = 12, critDamage = 24),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_ember_ring_uncommon",
            dungeonId = "dng_forge",
            family = "forge_ember_ring",
        ),
        EquipmentItem(
            id = "forge_anvil_ring_rare",
            name = "Sceau de l'enclume",
            slot = EquipmentSlot.RING,
            rarity = Rarity.RARE,
            stats = StatBlock(critRate = 13, critDamage = 30, defense = 10),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_anvil_ring_rare",
            dungeonId = "dng_forge",
            family = "forge_anvil_ring",
        ),
        EquipmentItem(
            id = "forge_anvil_ring_epic",
            name = "Sceau de l'enclume hurlante",
            slot = EquipmentSlot.RING,
            rarity = Rarity.EPIC,
            stats = StatBlock(critRate = 18, critDamage = 46, defense = 15, armorPierce = 12),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_anvil_ring_epic",
            dungeonId = "dng_forge",
            family = "forge_anvil_ring",
        ),
        EquipmentItem(
            id = "forge_bellows_uncommon",
            name = "Soufflet ardent",
            slot = EquipmentSlot.RELIC,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(magicPower = 20, lifeSteal = 6),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_bellows_uncommon",
            dungeonId = "dng_forge",
            family = "forge_bellows",
        ),
        EquipmentItem(
            id = "forge_bellows_epic",
            name = "Soufflet du Cœur de Fonte",
            slot = EquipmentSlot.RELIC,
            rarity = Rarity.EPIC,
            stats = StatBlock(magicPower = 38, lifeSteal = 12, hpRegen = 6, lootBonus = 12),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_forge_bellows_epic",
            dungeonId = "dng_forge",
            family = "forge_bellows",
        ),
        EquipmentItem(
            id = "forge_forge_draught_rare",
            name = "Trempe du forgeron",
            slot = EquipmentSlot.CONSUMABLE,
            rarity = Rarity.RARE,
            stats = StatBlock.EMPTY,
            passive = ItemPassive.NONE,
            healPercent = 0.8f,
            iconRes = "gear_forge_forge_draught_rare",
            dungeonId = "dng_forge",
            family = "forge_forge_draught",
        ),
    )
    /** The 20 pieces that only drop inside [DungeonCatalog.VOID]. */
    val VOID_GEAR: List<EquipmentItem> = listOf(
        EquipmentItem(
            id = "void_angle_edge_common",
            name = "Arête impossible",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.COMMON,
            stats = StatBlock(attack = 20),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_angle_edge_common",
            dungeonId = "dng_void",
            family = "void_angle_edge",
        ),
        EquipmentItem(
            id = "void_angle_edge_uncommon",
            name = "Arête impossible repliée",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(attack = 32, dodge = 7),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_angle_edge_uncommon",
            dungeonId = "dng_void",
            family = "void_angle_edge",
        ),
        EquipmentItem(
            id = "void_angle_edge_rare",
            name = "Arête impossible récursive",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.RARE,
            stats = StatBlock(attack = 42, dodge = 11, critDamage = 30),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_angle_edge_rare",
            dungeonId = "dng_void",
            family = "void_angle_edge",
        ),
        EquipmentItem(
            id = "void_rift_claw_uncommon",
            name = "Griffe de faille",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(attack = 34, armorPierce = 14),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_rift_claw_uncommon",
            dungeonId = "dng_void",
            family = "void_rift_claw",
        ),
        EquipmentItem(
            id = "void_rift_claw_epic",
            name = "Griffe de faille béante",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.EPIC,
            stats = StatBlock(attack = 50, armorPierce = 26, lifeSteal = 13, critRate = 11),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_rift_claw_epic",
            dungeonId = "dng_void",
            family = "void_rift_claw",
        ),
        EquipmentItem(
            id = "void_echo_blade_rare",
            name = "Lame en écho",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.RARE,
            stats = StatBlock(attack = 40, critRate = 13, critDamage = 28),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_echo_blade_rare",
            dungeonId = "dng_void",
            family = "void_echo_blade",
        ),
        EquipmentItem(
            id = "void_hem_legendary",
            name = "Ourlet du Réel",
            slot = EquipmentSlot.WEAPON,
            rarity = Rarity.LEGENDARY,
            stats = StatBlock(attack = 62, critRate = 20, critDamage = 70, armorPierce = 35),
            passive = ItemPassive.ARMOR_PIERCE,
            healPercent = 0f,
            iconRes = "gear_void_hem_legendary",
            dungeonId = "dng_void",
            family = "void_hem",
        ),
        EquipmentItem(
            id = "void_void_weave_common",
            name = "Tissage du vide",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.COMMON,
            stats = StatBlock(maxHp = 105),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_void_weave_common",
            dungeonId = "dng_void",
            family = "void_void_weave",
        ),
        EquipmentItem(
            id = "void_void_weave_uncommon",
            name = "Tissage du vide dense",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(maxHp = 175, dodge = 9),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_void_weave_uncommon",
            dungeonId = "dng_void",
            family = "void_void_weave",
        ),
        EquipmentItem(
            id = "void_void_weave_rare",
            name = "Tissage du vide insondable",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.RARE,
            stats = StatBlock(maxHp = 235, dodge = 14, defense = 22),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_void_weave_rare",
            dungeonId = "dng_void",
            family = "void_void_weave",
        ),
        EquipmentItem(
            id = "void_mirror_plate_rare",
            name = "Plates-miroirs",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.RARE,
            stats = StatBlock(maxHp = 250, defense = 26, thorns = 20),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_mirror_plate_rare",
            dungeonId = "dng_void",
            family = "void_mirror_plate",
        ),
        EquipmentItem(
            id = "void_mirror_plate_epic",
            name = "Plates-miroirs affamées",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.EPIC,
            stats = StatBlock(maxHp = 350, defense = 40, thorns = 32, lifeSteal = 10),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_mirror_plate_epic",
            dungeonId = "dng_void",
            family = "void_mirror_plate",
        ),
        EquipmentItem(
            id = "void_repeater_legendary",
            name = "Robe de Celle Qui Se Répète",
            slot = EquipmentSlot.ARMOR,
            rarity = Rarity.LEGENDARY,
            stats = StatBlock(maxHp = 400, defense = 44, dodge = 22, damageReduction = 16),
            passive = ItemPassive.RIPOSTE,
            healPercent = 0f,
            iconRes = "gear_void_repeater_legendary",
            dungeonId = "dng_void",
            family = "void_repeater",
        ),
        EquipmentItem(
            id = "void_star_ring_common",
            name = "Anneau de constellation morte",
            slot = EquipmentSlot.RING,
            rarity = Rarity.COMMON,
            stats = StatBlock(critRate = 10),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_star_ring_common",
            dungeonId = "dng_void",
            family = "void_star_ring",
        ),
        EquipmentItem(
            id = "void_star_ring_uncommon",
            name = "Anneau de constellation éteinte",
            slot = EquipmentSlot.RING,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(critRate = 17, critDamage = 34),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_star_ring_uncommon",
            dungeonId = "dng_void",
            family = "void_star_ring",
        ),
        EquipmentItem(
            id = "void_axiom_ring_rare",
            name = "Sceau d'axiome brisé",
            slot = EquipmentSlot.RING,
            rarity = Rarity.RARE,
            stats = StatBlock(critRate = 19, critDamage = 42, magicPower = 18),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_axiom_ring_rare",
            dungeonId = "dng_void",
            family = "void_axiom_ring",
        ),
        EquipmentItem(
            id = "void_axiom_ring_epic",
            name = "Sceau d'axiome effondré",
            slot = EquipmentSlot.RING,
            rarity = Rarity.EPIC,
            stats = StatBlock(critRate = 25, critDamage = 62, magicPower = 28, lootBonus = 18),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_axiom_ring_epic",
            dungeonId = "dng_void",
            family = "void_axiom_ring",
        ),
        EquipmentItem(
            id = "void_silence_uncommon",
            name = "Nœud de silence",
            slot = EquipmentSlot.RELIC,
            rarity = Rarity.UNCOMMON,
            stats = StatBlock(magicPower = 32, dodge = 8),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_silence_uncommon",
            dungeonId = "dng_void",
            family = "void_silence",
        ),
        EquipmentItem(
            id = "void_silence_epic",
            name = "Nœud de silence absolu",
            slot = EquipmentSlot.RELIC,
            rarity = Rarity.EPIC,
            stats = StatBlock(magicPower = 58, dodge = 15, hpRegen = 10, damageReduction = 9),
            passive = ItemPassive.NONE,
            healPercent = 0f,
            iconRes = "gear_void_silence_epic",
            dungeonId = "dng_void",
            family = "void_silence",
        ),
        EquipmentItem(
            id = "void_void_draught_epic",
            name = "Gorgée de néant",
            slot = EquipmentSlot.CONSUMABLE,
            rarity = Rarity.EPIC,
            stats = StatBlock.EMPTY,
            passive = ItemPassive.NONE,
            healPercent = 1.0f,
            iconRes = "gear_void_void_draught_epic",
            dungeonId = "dng_void",
            family = "void_void_draught",
        ),
    )

    /** Every dungeon-specific piece, flattened. */
    val ALL: List<EquipmentItem> = CRYPT_GEAR + FORGE_GEAR + VOID_GEAR

    private val byDungeon: Map<String, List<EquipmentItem>> = ALL.groupBy { it.dungeonId!! }

    fun gearOf(dungeonId: String): List<EquipmentItem> = byDungeon[dungeonId].orEmpty()

    fun gearOf(dungeonId: String, rarity: Rarity): List<EquipmentItem> =
        gearOf(dungeonId).filter { it.rarity == rarity }
}
